### ISSUE TITLE
Label support in assembly

### ISSUE THREAD

**Issue by jserv** [jserv/full-stack-hello#28]
Recently, @pakls contributed a series of conditional branch instructions which enables further translation from higher level languages to our virtual machine. However, lacking of labels prevents jump instructions from being efficiently used.

Thus, we expect that assembler can recognize labels as the indicators of open/close loop or deterministic location.

**Comment by mlouielu** [comment]
For reference, here is x86 labels reference: https://docs.oracle.com/cd/E19120-01/open.solaris/817-5477/esqaq/index.html

Symbolic labels should be easy to implement.

**Comment by pakls** [comment]
@HexRabbit completed it in 5baad29.
