### ISSUE TITLE
Stack and push/pop/call/ret support

### ISSUE THREAD

**Issue by pakls** [jserv/full-stack-hello#31]
Hi @jserv @mlouielu,

Shall the instruction set to be expanded to support stack?

**Comment by mlouielu** [comment]
That will be a nice feature to support this. But we didn't introduce some special control register now (ebp, eip, ...etc). Maybe we should first introduce this?

**Comment by pakls** [comment]
AFAIK, there are a few ways to implement the registers:

1. Intel x86 style
2. RISC, general purpose style
3. Memory based, that is, all registers are integers in memory at certain locations.

I am wondering is there any design of 3?
